spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 706138419343-sonv0c5lbos4bpjqjd10lo1c0vr0k79k.apps.googleusercontent.com
                        client-secret: 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
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/chatapp
        username: postgres
        password: "#1Foofighters"
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    main:
        allow-circular-references: true

logging:
    level:
        root: info


app:
    token-secret: 396fc75a42d4a811d97e462dc54fcbd25023e644156df363a212a8832f5447da
    token-expiration-msec: 864000000
    cookie-name: user-cookie
    authorized-redirect-uris: >
        http://localhost:8080/,
        http://localhost:3000/

