spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 706138419343-sonv0c5lbos4bpjqjd10lo1c0vr0k79k.apps.googleusercontent.com
                        client-secret: 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
    r2dbc:
        url: r2dbc:postgresql://localhost:5432/chatapp
        username: postgres
        password: "#1Foofighters"
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level:
        root: info


app:
    token-secret: oD6H8sRyxfeXQsv2jnnHy2FQ8C2tzNbU
    token-expiration-msec: 864000000
    cookie-name: user-cookie

